version : '3'

services:
  mysqlite:
    image : "drupalci/sqlite-3:production"
    volumes :
      - sqlite-data:/assignmentdata
    ports :
     - "5432:5432"
    
  web:
    build: .
    ports:
      - '7755:7755'

volumes:
  sqlite-data:

